{% set version = "0.1.0" %}

package:
  name: xdmfwrite_h5py
  version: {{ version }}

source:
  url: https://github.com/tdegeus/XDMFWrite_h5py/archive/v{{ version }}.tar.gz
  sha256: fda5614728a0a5929daf10b69a82b7a1fa79ffe4340145c58060a66c6549458d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - h5py

test:
  imports:
    - XDMFWrite_h5py

about:
  home: https://github.com/tdegeus/XDMFWrite_h5py
  license: MIT
  license_file: LICENSE
  summary: Write XDMF files to interpret HDF5 files.
  description: Write XDMF files to interpret HDF5 files.
  doc_url: https://github.com/tdegeus/XDMFWrite_h5py
  dev_url: https://github.com/tdegeus/XDMFWrite_h5py

extra:
  recipe-maintainers:
    - tdegeus
